package no.meikle.hockey_smash.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "remember-me")
public class RememberMe {

	@DynamoDBRangeKey
	@DynamoDBAutoGeneratedKey
	private String key;
	private String userKey;
	@DynamoDBHashKey
	private String teamKey;
	private String passwordHash;

	public RememberMe(User aUser) {

		this.setUserKey(aUser.getKey());
		this.setTeamKey(aUser.getTeam());
		this.setPasswordHash(aUser.getPasswordHash());

	}

	public RememberMe() {

	}
	
	public String getPasswordHash() {
		return passwordHash;
	}

	public void setPasswordHash(String aPassword) {

		this.passwordHash = aPassword;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getUserKey() {
		return userKey;
	}

	public void setUserKey(String userKey) {
		this.userKey = userKey;
	}

	public String getTeamKey() {
		return teamKey;
	}

	public void setTeamKey(String teamKey) {
		this.teamKey = teamKey;
	}

	@DynamoDBIgnore
	public String getCookieValue() {
		return this.getTeamKey() + "!" + this.getKey();
	}

}
