package no.meikle.hockey_smash.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "teams")
public class Team {

	public static final Team ADMIN_TEAM = new Team(User.ADMIN_STRING, User.ADMIN_STRING);

	private Team(String key, String name) {
		this();
		this.key = key;
		this.name = name;
	}

	public Team() {
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String key;
	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

}
