package no.meikle.hockey_smash.domain.old;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Deprecated
@DynamoDBTable(tableName = "teams-2")
public class Team2 {

	private Team2(String key, String name) {
		this();
		this.key = key;
		this.name = name;
	}

	public Team2() {
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String key;
	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

}
